### ISSUE TITLE
Cannot send a content-body with this verb-type.

### ISSUE THREAD

**Issue by DeniseDornell** [klarna/kco_rest_dotnet#27]
Client.Checkout.GetOrder(orderId).Result and Client.OrderManagement.GetOrder(orderId).Result  is just awaiting without any result

It works if I create a own request with HttpClient

**Comment by martingust** [comment]
@DeniseDornell Do you get any errors? 

You can try inspect to see the request and response JSON? You can implement a custom JSON serializer in order to do that https://github.com/klarna/kco_rest_dotnet/blob/v3.0/Klarna.Rest/Klarna.Rest.Core.Examples/CustomJsonSerializer.cs

Also what happens if you use `async/await` instead of `.Result`? Do you get any better error?

**Comment by ErikGranly** [comment]
Getting the following error using both these methods(Client.Checkout.GetOrder(orderId).Result and Client.OrderManagement.GetOrder(orderId).Result )

Details:
Cannot send a content-body with this verb-type.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.ProtocolViolationException: Cannot send a content-body with this verb-type.
Stack Tace:

[ProtocolViolationException: Cannot send a content-body with this   verb-type.]      
System.Net.HttpWebRequest.CheckProtocol(Boolean   onRequestStream) +6793482        
System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback,   Object state) +59      
System.Net.Http.HttpClientHandler.StartGettingRequestStream(RequestState   state) +129        
System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState   state) +307        
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99     
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task) +58        
Klarna.Rest.Core.Commuication.<MakeRequest>d__13.MoveNext() +430        
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99      
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task) +58        
Klarna.Rest.Core.Commuication.<Get>d__10`1.MoveNext() +194        
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99        
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task   task) +58     
Klarna.Rest.Core.Store.<GetOrder>d__2.MoveNext()   +176

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_dotnet/pull/35

**Comment by alexions** [comment]
Thanks to the **Guillermo**

With his help we found an issue (I suppose for the older versions of .NET Core) when sending the GET requests.

HTTP 1.1. Specification says, that GET request should not have a body (but it can have), but the reality, you will get a verb-type exception when sending the GET with a body inside.

So the fix allows to set null when no body data instead of string.Empty

**Comment by freethan** [comment]
Resolved by #35 , please get in touch if the issue persists
