### ISSUE TITLE
klarna_reference missing from CheckoutOrder

### ISSUE THREAD

**Issue by kwestground** [klarna/kco_rest_dotnet#53]
CheckoutOrder does not map "klarna_response"

https://github.com/klarna/kco_rest_dotnet/blob/v3.x/Klarna.Rest/Klarna.Rest.Core/Model/CheckoutOrder.cs

https://developers.klarna.com/api/#order-management-api-get-order

**Comment by alexions** [comment]
Hi @kwestground 

Thanks for the feedback. 

You are right, the CheckoutOrder has no such field and actually it should not by two reasons:
1) The Klarna Checkout service differs from the Klarna Order Management service. You can consider them as two separated services, so they can have a different Order models
2) The most important part is, the field itself:

`klarna_reference A Klarna generated reference that is shorter than the Klarna Order Id and is used as a customer friendly reference. It is most often used as a reference when Klarna is communicating with the customer with regard to payment statuses.`

So this is a "friendly representation" of the created order. Since the checkout processes an order and it is not placed yet by customer, you cannot have such field (you can consider the order like "does not exist yet") and that's why the CheckoutOrder model has no such field. But after the order is placed - this reference will be generated and then you can use it.

Klarna Checkout says, that after placing an order use the Order Management to get the details. So using the Order Management you can finally get the klarna_reference.

By the way, thanks for pointing us to the models, we actualized them by adding missing fields (not related to the klarna_reference but still important).

Thanks!

**Comment by alexions** [comment]
Fixed in https://www.nuget.org/packages/Klarna.Rest.Core/3.1.4
