### ISSUE TITLE
Async/Await issue

### ISSUE THREAD

**Issue by agnerbo** [klarna/kco_rest_dotnet#54]
**Describe the bug**
When using GetOrder the task never retruns. It can be fixed by adding .ConfigureAwait(false) when using async.

Async/Await - Best Practices in Asynchronous Programming
https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

**Which service do you use**
Every call to klarna

**To Reproduce**
var klarnaEnv = isTest ? KlarnaEnvironment.TestingEurope : KlarnaEnvironment.LiveEurope;
var klarnaApi = new Klarna.Rest.Core.Klarna(username, password, klarnaEnv);
var task = klarnaApi.OrderManagement.GetOrder(klarnaOrderId);
task.Wait(TimeSpan.FromMinutes(1));

**Expected behavior**
Wait to terminate when order has been recieved

**Additional context**

**Comment by igeligel** [comment]
I think you did run into a deadlock situation. You can read more about it here: https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

Since you are working currently with this version of the Klarna SDK you should pass down the async context of your application the whole way down as mentioned in the article:

> Don’t block on Tasks; use async all the way down.

The other option is:

> In your “library” async methods, use ConfigureAwait(false) wherever possible.

which is on us. So we would need to create a new release, but we are happy to receive a PR including the changes. There is also another blog article explaining the `ConfigureAwait` in detail: https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

--- 

This is the code as it is right now in [`Klarna.Rest.Core/Store/OrderManagementStore.cs`](https://github.com/klarna/kco_rest_dotnet/blob/v3.x/Klarna.Rest/Klarna.Rest.Core/Store/OrderManagementStore.cs#L106-L113)

```csharp
public async Task<OrderManagementOrder> GetOrder(string orderId)
{
    var url = ApiUrlHelper.GetApiUrlForController(ApiSession.ApiUrl, ApiControllerUri, $"{orderId}");
    var response = await Get<OrderManagementOrder>(url);
    return response;
}
```

But it should look like this:

```csharp
public async Task<OrderManagementOrder> GetOrder(string orderId)
{
    var url = ApiUrlHelper.GetApiUrlForController(ApiSession.ApiUrl, ApiControllerUri, $"{orderId}");
    return await Get<OrderManagementOrder>(url).ConfigureAwait(false);
}
```

**Comment by alexions** [comment]
The fix is coming: https://github.com/klarna/kco_rest_dotnet/pull/55

**Comment by alexions** [comment]
@igeligel added as a reviewer

**Comment by alexions** [comment]
Merged. The changes will appear in the next release.

**Comment by alexions** [comment]
Fixed in https://www.nuget.org/packages/Klarna.Rest.Core/3.1.4
