### ISSUE TITLE
Allow usage of WebProxy in HttpClient

### ISSUE THREAD

**Issue by Taturevich** [klarna/kco_rest_dotnet#66]
We want to utilize Klarna.Rest.Core package in order to make integration with Klarna api. One of our customer requirements is to proxy all network calls to external domains through proxy. Current implementation of rest client hides HttpHandler deeply inside library, thus complicating this particular scenario. .NET Core also does not support global proxy for all out coming calls.

Ideally we are wanting to do something like this:
```
var proxy = new WebProxy
{
      BypassProxyOnLocal = true,
      Address = new Uri($"http://{_proxySettings.Value.ProxyHost}:{_proxySettings.Value.ProxyPort}"),
};
var httpClientHandler = new HttpClientHandler
{
      Proxy = proxy,
      UseProxy = true,
};
```

Is this possible to extend current functionality to allow passing of proxy object into handler? Or provide way to pass custom HttpClient into client during it's creation.
Thanks in advance!

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_dotnet/pull/71

**Comment by alexions** [comment]
Thanks for the PR! I partially used your proposed changes in the PR #71 . 

Due to the huge change about fixing the typo in the major namespace Communication (was Commuication before the fix) your PR now has conflicts. In order to increase the changes delivery time I will close your PR and merge #71 . This will allow us to release the new SDK version today (14th Oct) or tomorrow.

Check the release notes!
