### ISSUE TITLE
Missing Payment Method categories property in HostedPaymentPageOptions

### ISSUE THREAD

**Issue by mnording** [klarna/kco_rest_dotnet#77]
It is not possible to define the payment method categories as an array when defining the options

https://developers.klarna.com/api/#hosted-payment-page-api__create-a-new-hpp-session__options

**Comment by alexions** [comment]
Fixed in this PR: https://github.com/klarna/kco_rest_dotnet/pull/79

Actually - this is not just a fix by adding a missing field. We started a migration to auto-generated models. So in order to use Payment Method categories you need to start using new models. 

We have Obsolete annotation that points to the new model name with all the new fields.
