### ISSUE TITLE
Promo codes (custom payment methods) contract issue

### ISSUE THREAD

**Issue by Taturevich** [klarna/kco_rest_dotnet#83]
During integration with Klarna we found possible bug related to promo codes functionality. 
There is a contract in `PaymentOrder` class:
```
[JsonProperty(PropertyName = "customer_payment_method_ids")]
public ICollection<string> CustomPaymentMethodIds { get; set; } 
```
After conversation with support team we was told that instead of
_"customer_payment_method_ids"_ we should use _"custom_payment_method_ids"_ while sending create session call. Requests from postman with _"custom_payment_method_ids"_ result in success and payment methods offered by promo codes are displayed on widget.

Could someone please take a look at that?

**Comment by alexions** [comment]
Hello @Taturevich 

Thanks for creating a PR. I can confirm that there are some issues with models, like missing fields or typos in the JSON representation. That's why we decided to migrate to auto-generated models.

In the PR #85 I created all the new models that support all the latest features and fields and have no such issue with typos. These models are not manually written, but auto-generated. Releasing these changes will take some time, because we need to code-review the changes and prepare a release package, but I hope it will not take too much time.

I will cancel your PR since PR #85 has all the required changes. Please follow this ticket to track the changes and release progress.

Best wishes!
