### ISSUE TITLE
PaymentAPI problems with response results

### ISSUE THREAD

**Issue by kthor-nue** [klarna/kco_rest_dotnet#97]
Hi Team,

We want to use the PaymentAPI to make Pay Later available within our Web Shop (direct integration by REST Api).

Therefore I used the MVC WebApp example as a blueprint.
I create a PaymentCreditSession object do the call to the API

(HomeController.cs lines 143/144):

`var response = client.Payment.CreateCreditSession(paymentSession);`
`var creditSession = response.Result;`

The first line of this is executed and I can see in the (European) Klarna Playground that the data was received.
Unfortunately the process stucks in the second line.

This also happens when I add
`response.ConfigureAwait(true);`
after the first line as I found in another issue.

To exclude problems with our company network I also tried this from a totally different network.

I tried this with SDK versions 3.1.9 and 3.1.10 and .NET versions 4.61 and 4.72. Environments are Windows 10 Pro (as localhost for development) and 2008R2 (staging environment)

Thanks and best regards

**Comment by AlexACD21** [comment]
This is because of a bug in the SDK that causes deadlock (ConfigureAwait isn't called all the way down to await HttpClient.SendAsync(httpMessage) in BaseRestClient.MakeRequest, which captures your asp.net mvc synchronization context)

You can workaround it by offloading wait for task completion to the thread pool: 
var creditSession = Task.Run(() => client.Payment.CreateCreditSession(paymentSession)).GetAwaiter().GetResult()

**Comment by kthor-nue** [comment]
Hi Alex!

This seems to solve the problem!

Thanks a million!
